version: '3.9'

services:
  server:
    build:
      context: .
    container_name: server
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/doctoranywhere
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SQL_DIALECT=org.hibernate.dialect.MySQLDialect
    ports:
      - "8080:8080"
    networks:
      - backend
  db:
    image: mysql:8
    container_name: db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 5s
    ports:
      - "3309:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: postgres
      MYSQL_PASSWORD: postgres
      MYSQL_DATABASE: doctoranywhere
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend  
  
# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend: